name: Build Resume

on:
  push:
    paths:
      - '**.tex'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t resume-builder .

      - name: Create container & extract PDF
        run: |
          container=$(docker create resume-builder)
          docker cp $container:/cv/main.pdf ./main.pdf
          docker rm $container

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume PDF
          path: main.pdf
